const IC={today:'<circle cx=12 cy=12 r=9 /><path d="M8.5 12.5l2.5 2.5 4.5-5" />',book:'<path d="M5 4h11a3 3 0 013 3v13H8a3 3 0 01-3-3z" /><path d="M5 17a3 3 0 013-3h11" />',cal:'<rect x=3 y=5 width=18 height=16 rx=3 /><path d="M3 10h18M8 3v4M16 3v4" />',chart:'<path d="M5 20V11M12 20V4M19 20v-6" />',sliders:'<path d="M4 7h9M17 7h3M4 17h3M11 17h9" /><circle cx=15 cy=7 r=2 /><circle cx=9 cy=17 r=2 />',plus:'<path d="M12 5v14M5 12h14" />',x:'<path d="M6 6l12 12M18 6L6 18" />',search:'<circle cx=11 cy=11 r=7 /><path d="M20 20l-4-4" />',star:'<path d="M12 3l2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z" />',copy:'<rect x=9 y=9 width=11 height=11 rx=2.5 /><path d="M5 15V7a3 3 0 013-3h8" />',trash:'<path d="M4 7h16M10 11v6M14 11v6M6 7l1 13h10l1-13M9 7V4h6v3" />',flame:'<path d="M12 3c1 4 5 5 5 10a5 5 0 01-10 0c0-2 1-3 2-4 0 2 1 3 2 3 0-3-1-5 1-9z" />',check:'<path d="M5 12.5l4.5 4.5L19 7" />',down:'<path d="M12 4v11M7 10l5 5 5-5M5 20h14" />',up:'<path d="M12 16V5M7 10l5-5 5 5M5 20h14" />',link:'<path d="M10 14a4 4 0 005.7 0l3-3a4 4 0 00-5.7-5.7l-1 1M14 10a4 4 0 00-5.7 0l-3 3a4 4 0 005.7 5.7l1-1" />'};
const ic=(n,f)=>`<svg class=ic viewBox="0 0 24 24" fill=${f?'currentColor':'none'} stroke=currentColor stroke-width=1.8 stroke-linecap=round stroke-linejoin=round>${IC[n]}</svg>`;
const sc=si=>'s'+SUB[si][1],syi=c=>`<span class="sy ${c||''}" data-sy=${sy}><i></i><span>${SYL[sy]}</span></span>`;
const TABS=[['Today','today'],['Chapters','book'],['Plan','cal'],['Stats','chart'],['Settings','sliders']];
const vSide=()=>`<div class=lg><svg viewBox="0 0 64 64"><rect width=64 height=64 rx=15 fill="#eceff5" /><path d="M44 21.5A15.4 15.4 0 1 0 47.4 33.5H33" fill=none stroke="#0a0b0e" stroke-width=6.5 stroke-linecap=round /></svg><b>Grind</b></div><nav>${TABS.map((t,i)=>`<button class="${ui.tab===i?'on':''}" data-a=tab data-t=${i}>${ic(t[1])}<span>${t[0]}</span></button>`).join('')}</nav>${syi('dsk')}`;
const head=(t,s,r='')=>`<header class=hd><div><h1>${t}</h1><p>${s}</p></div><div class=hr>${r}${syi('mob')}</div></header>`;
const mo=(c,n)=>`<div class="mo ${n||''}">${c.map(v=>`<i class="${v?'on':''}"></i>`).join('')}</div>`;
const strip=a=>`<section class=strip>${a.map(x=>`<div><span>${x[1]}</span><b>${x[0]}</b><small>${x[2]}</small></div>`).join('')}</section>`;
const chip=x=>{const c=C(x.id);return`<span class="chp ${sc(x.si)}"><i></i>${esc(c.n)}<em>L${x.li+1}</em></span>`};
const tk=x=>{const c=C(x.id),nd=c.d.findIndex(v=>!v);return`<div class="tk ${sc(x.si)}"><button class=ck data-a=l data-id="${c.id}" data-i=${x.li} aria-label="Mark lecture done">${ic('check')}</button><div class=tx><b>${esc(c.n)}</b><span>${SUB[x.si][0]} · Lecture ${x.li+1} of ${c.L}${c.p?' · Priority':''}</span></div>${nd>=0?`<button class="btn sm" data-a=nd data-id="${c.id}">DPP ${nd+1}</button>`:''}</div>`};
const dn=x=>`<div class="tk dn ${sc(x.si)}"><button class="ck on" data-a=l data-id="${x.id}" data-i=${x.li} aria-label="Undo">${ic('check')}</button><div class=tx><b>${esc(C(x.id).n)}</b><span>Lecture ${x.li+1} · tap to undo</span></div></div>`;
function vToday(){const p=plan(),s=stats(),T=TD(),z=status(p),pc=s.L?Math.round(s.a/s.L*100):0,cur=p.out[0]&&p.out[0].d===T?p.out[0]:null;
const cd=Math.max(0,Math.ceil((new Date(st.m.end+'T00:00')-new Date().setHours(0,0,0,0))/864e5)),wk=arr(7,i=>glog(back(i))[0]).reduce((a,b)=>a+b,0),tl=glog(T);
const nx=p.out.slice(cur?1:0).find(x=>x.it.length),fin=[...p.out].reverse().find(x=>x.it.length),rv=st.ch.filter(c=>c.c&&c.c<=2&&done(c)).sort((a,b)=>a.c-b.c)[0];
return head('Today',fd(T),`<span class="pill ${z[1]}">${z[0]}</span>`)+strip([[pc+'%','Complete',s.a+' of '+s.L+' lectures'],[cd,'Days left',fin?'Finish '+fd(fin.d):'Nothing pending'],[wk+'<u>/'+st.m.goal+'</u>','This week','Lectures'],[streak(),'Day streak',tl[0]+' lectures today']])+
`<div class=g21><section class=pn><div class=pt><h3>Queue</h3>${cur&&p.left?`<button class="btn sm" data-a=more>${ic('plus')}One more</button>`:''}</div>
${!st.ch.length?"<div class=em><strong>No chapters yet.</strong><br><span class=mu>Add your first chapter to build today's queue.</span></div>":!cur?'<div class=em>Rest day. Nothing scheduled.</div>':cur.it.length?cur.it.map(tk).join(''):'<div class=em>Queue clear. Nice work.</div>'}${p.dT.map(dn).join('')}</section>
<div class=col><section class=pn><div class=pt><h3>Subjects</h3></div><div class=sb>${SUB.map((sb,si)=>{const cs=sub(si),L=cs.reduce((a,c)=>a+c.L,0),a=cs.reduce((n,c)=>n+done(c),0);return`<div class="${sc(si)}"><div class=sl><span>${sb[0]}</span><b>${a}<u>/${L}</u></b></div>${mo(cs.flatMap(c=>c.l),'sm')}</div>`}).join('')}</div></section>
${nx?`<section class=pn><div class=pt><h3>Up next</h3><span class=mu>${fd(nx.d)}</span></div><div class=chs>${nx.it.map(chip).join('')}</div></section>`:''}
${rv?`<section class=pn><div class=pt><h3>Revise</h3></div><div class="tk ${sc(rv.s)}" style="border:0"><div class=tx><b>${esc(rv.n)}</b><span>Confidence ${rv.c}/5</span></div><button class="btn sm" data-a=open data-id="${rv.id}">Open</button></div></section>`:''}</div></div>`}
const card=c=>`<div class="cd ${sc(c.s)}" data-a=open data-id="${c.id}" tabindex=0 role=button><div class=cm><span>${SUB[c.s][0]}</span>${c.p?`<em>${ic('star',1)}</em>`:''}${c.c?`<small>${c.c}/5</small>`:''}</div><h4>${esc(c.n)}</h4>${mo(c.l)}<div class=cb><span>${done(c)}/${c.L} lectures · ${dpp(c)}/${c.D} DPP</span>${done(c)<c.L?`<button class="btn ib sm" data-a=nl data-id="${c.id}" aria-label="Mark next lecture done">${ic('plus')}</button>`:`<span class=okc>${ic('check')}</span>`}</div></div>`;
function cards(){const q=ui.q.toLowerCase();let l=st.ch.filter(c=>(ui.f<0||c.s===ui.f)&&(!q||c.n.toLowerCase().includes(q))).sort((a,b)=>a.s-b.s||a.o-b.o);
if(ui.so===1)l.sort((a,b)=>(a.c||9)-(b.c||9)||a.s-b.s);if(ui.so===2)l.sort((a,b)=>ratio(a)-ratio(b));
return l.length?`<div class=cg>${l.map(card).join('')}</div>`:'<div class=em>No chapters match.</div>'}
const seg=(a,cur,act)=>`<div class=sg>${a.map(x=>`<button class="${cur===x[1]?'on':''}" data-a=${act} data-v=${x[1]}>${x[0]}</button>`).join('')}</div>`;
function vChapters(){return head('Chapters',st.ch.length+' chapters',`<button class="btn pri" data-a=addm>${ic('plus')}New chapter</button>`)+
`<div class=tb><label class=sr>${ic('search')}<input id=qs placeholder="Search chapters" value="${esc(ui.q)}" autocomplete=off></label>${seg([['All',-1],...SUB.map((s,i)=>[s[0],i])],ui.f,'fs')}${seg([['Order',0],['Weakest',1],['Progress',2]],ui.so,'so')}</div><div id=grid>${cards()}</div>`}
const stp=(id,k,v)=>`<div class=stp><button data-a=cnt data-id="${id}" data-k=${k} data-v=-1 aria-label=Less>−</button><b>${v}</b><button data-a=cnt data-id="${id}" data-k=${k} data-v=1 aria-label=More>+</button></div>`;
function vDrawer(c){const id=c.id;return`<div class=bd data-a=close><div class="dr ${sc(c.s)}" data-a=noop><div class=dh><span class=sn>${SUB[c.s][0]}</span><button class="btn ib" data-a=close aria-label=Close>${ic('x')}</button></div><div class=db>
<input class=nm id=nm data-id="${id}" value="${esc(c.n)}" maxlength=80 aria-label="Chapter name">
<div class=kp><div><b>${done(c)}<u>/${c.L}</u></b><span>Lectures</span></div><div><b>${dpp(c)}<u>/${c.D}</u></b><span>DPPs</span></div><div><b>${c.c||'–'}</b><span>Confidence</span></div></div>
<div class=sc><div class=st><h5>Lectures</h5>${stp(id,'L',c.L)}</div><div class=dts>${c.l.map((v,i)=>`<button class="${v?'on':''}" data-a=l data-id="${id}" data-i=${i}>${i+1}</button>`).join('')||'<span class=mu>None</span>'}</div></div>
<div class=sc><div class=st><h5>DPPs</h5>${stp(id,'D',c.D)}</div><div class=dts>${c.d.map((v,i)=>`<button class="${v?'on':''}" data-a=d data-id="${id}" data-i=${i}>${i+1}</button>`).join('')||'<span class=mu>None</span>'}</div></div>
<div class=ac><button class="btn sm" data-a=allc data-id="${id}">Mark all done</button><button class="btn sm" data-a=clr data-id="${id}">Clear</button></div>
<div class=sc><div class=st><h5>Confidence</h5><div class=stars>${[1,2,3,4,5].map(n=>`<button class="${c.c>=n?'on':''}" data-a=conf data-id="${id}" data-v=${n} aria-label="${n} of 5">${ic('star',1)}</button>`).join('')}</div></div></div>
<div class=sc><div class=st><h5>Priority</h5><button class="sw ${c.p?'on':''}" data-a=pin data-id="${id}" aria-label=Priority><i></i></button></div></div>
<div class=sc><h5>Notes</h5><textarea id=nt data-id="${id}" rows=4 maxlength=500 placeholder="Formulas, weak points, doubts">${esc(c.t)}</textarea></div>
<button class="btn dg" style="width:100%" data-a=del data-id="${id}">${ic('trash')}${ui.dc===id?'Tap again to delete':'Delete chapter'}</button></div></div></div>`}
function vAdd(){const m=ui.m;return`<div class="bd c" data-a=close><div class=md data-a=noop><h3>New chapter</h3>${seg(SUB.map((s,i)=>[s[0],i]),m.s,'asub')}<label>Name<input id=an value="${esc(m.n||'')}" maxlength=80 placeholder="Chapter name" autocomplete=off></label><div class=two><label>Lectures<input id=aL type=number min=0 max=60 value=${m.L}></label><label>DPPs<input id=aD type=number min=0 max=60 value=${m.D}></label></div><div class=ac><button class=btn data-a=close>Cancel</button><button class="btn pri" data-a=add>Add chapter</button></div></div></div>`}
const vLink=()=>`<div class="bd c" data-a=close><div class=md data-a=noop><h3>Link a device</h3><div class=kr><code>${key}</code><button class="btn ib" data-a=copy aria-label="Copy key">${ic('copy')}</button></div><label>Key from your other device<input id=lk placeholder="Paste key" autocomplete=off></label><div class=ac><button class=btn data-a=close>Cancel</button><button class="btn pri" data-a=apply>Link</button></div></div></div>`;
function vPlan(){const p=plan(),rows=p.out.filter(x=>x.it.length),T=TD(),sh=ui.all?rows:rows.slice(0,20);
return head('Plan',p.left+' lectures · '+p.ds.length+' study days')+`<section class=pn>${sh.map(r=>{const d=new Date(r.d+'T00:00');return`<div class="pr ${r.d===T?'now':''}"><div class=pd><b>${d.getDate()}</b><span>${d.toLocaleDateString('en-GB',{weekday:'short',month:'short'})}</span></div><div class=chs>${r.it.map(chip).join('')}</div></div>`}).join('')||'<div class=em>Everything is scheduled or done.</div>'}</section>`+(rows.length>20?`<div class=cn><button class=btn data-a=showall>${ui.all?'Show less':'Show all '+rows.length+' days'}</button></div>`:'')}
function vStats(){const p=plan();let t=[0,0],best=0,ad=0;Object.values(st.lg).forEach(m=>Object.values(m).forEach(a=>{t[0]+=a[0];t[1]+=a[1];best=Math.max(best,a[0]);if(a[0]+a[1])ad++}));
const now=new Date(),start=new Date(now);start.setDate(now.getDate()-now.getDay()-98);let cells='';
for(let i=0;i<105;i++){const d=new Date(start);d.setDate(start.getDate()+i);if(d>now){cells+='<i class=x></i>';continue}const a=glog(iso(d)),v=a[0]+a[1];cells+=`<i class="${v?'h'+Math.min(4,Math.ceil(v/2)):''}" title="${iso(d)} · ${v}"></i>`}
const last=arr(14,i=>{const d=back(13-i);return[glog(d)[0],new Date(d+'T00:00').toLocaleDateString('en-GB',{weekday:'narrow'})]}),mx=Math.max(1,...last.map(x=>x[0]));
return head('Stats','Your pace at a glance')+strip([[t[0],'Lectures logged','Since tracking'],[t[1],'DPPs logged','Since tracking'],[ad?(t[0]/ad).toFixed(1):0,'Per active day','Best day '+best],[p.ds.length?(p.left/p.ds.length).toFixed(1):'–','Needed per day','To finish on time']])+
`<div class=g11><section class=pn><div class=pt><h3>Last 14 days</h3></div><div class=bars>${last.map(x=>`<div><i style="height:${x[0]/mx*100}%"></i><span>${x[1]}</span></div>`).join('')}</div></section>
<section class=pn><div class=pt><h3>Consistency</h3></div><div class=heat>${cells}</div></section></div>
<section class=pn style="margin-top:16px"><div class=pt><h3>Subjects</h3></div>${SUB.map((sb,si)=>{const cs=sub(si),L=cs.reduce((a,c)=>a+c.L,0),a=cs.reduce((n,c)=>n+done(c),0),Dn=cs.reduce((a,c)=>a+c.D,0),b=cs.reduce((n,c)=>n+dpp(c),0),cf=cs.filter(c=>c.c),av=cf.length?(cf.reduce((n,c)=>n+c.c,0)/cf.length).toFixed(1):'–';
return`<div class="sw2 ${sc(si)}"><b>${sb[0]}</b><div class=bar><i style="width:${L?a/L*100:0}%"></i></div><span>${a}/${L} lectures</span><span>${b}/${Dn} DPPs</span><span>${av} ★</span></div>`}).join('')}</section>`}
const rw=(l,r)=>`<div class=rw><span>${l}</span>${r}</div>`;
function vSettings(){const T=TD(),ks=key.slice(0,6)+'…'+key.slice(-4);
const q=(k,v)=>`<div class=stp><button data-a=${k} data-v=-1>−</button><b>${v}</b><button data-a=${k} data-v=1>+</button></div>`;
return head('Settings','Schedule, sync and data')+`<div class=g11><section class=pn><div class=pt><h3>Schedule</h3></div>
${rw('Deadline',`<input type=date id=end value=${st.m.end}>`)}${rw('Lectures per day',q('q',st.m.q))}${rw('Weekly goal',q('g',st.m.goal))}
${rw('Days off',`<div class=dy>${DN.map((n,i)=>`<button class="${st.m.off.includes(i)?'on':''}" data-a=wd data-v=${i}>${n}</button>`).join('')}</div>`)}
${rw('Rest today',`<button class="sw ${st.m.od.includes(T)?'on':''}" data-a=rest aria-label="Rest today"><i></i></button>`)}</section>
<div class=col><section class=pn><div class=pt><h3>Cloud</h3>${syi()}</div>${rw(`<code>${ks}</code>`,`<button class="btn ib" data-a=copy aria-label="Copy key">${ic('copy')}</button>`)}<div class=rw><button class=btn style="width:100%" data-a=link>${ic('link')}Link a device</button></div></section>
<section class=pn><div class=pt><h3>Data</h3></div><div class="rw two"><button class=btn data-a=exp>${ic('down')}Export</button><label class=btn>${ic('up')}Import<input type=file id=imp accept=".json,application/json" hidden></label></div>
<div class=rw><button class="btn dg" style="width:100%" data-a=reset>${ui.rs?'Tap again to erase everything':'Reset all progress'}</button></div></section></div></div>`}
